// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    resources: {
      "/book": {
        get: {
          description: "returns books"
        }
      }
    }
  };

}).call(this);
